# Generated by Django 5.1.1 on 2024-10-07 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_userprofile_show_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='buffer_period',
            field=models.IntegerField(default=7),
        ),
    ]
