# Generated by Django 5.1.1 on 2024-09-15 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_userprofile_show_tooltip'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
